# Workflow pour construire et déployer un site Nuxt 3 sur GitHub Pages

name: Déployer le site Nuxt sur Pages

on:
  # S'exécute lors des push sur la branche par défaut
  push:
    branches: ["master"]

  # Permet d'exécuter ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

# Définit les permissions du jeton GITHUB_TOKEN pour permettre le déploiement sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Autoriser un seul déploiement simultané, en ignorant les exécutions mises en file d'attente entre l'exécution en cours et la dernière mise en file d'attente.
# Cependant, ne PAS annuler les exécutions en cours car nous voulons permettre à ces déploiements de production de se terminer.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Tâche de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configuration de PNPM
      - name: Configuration de PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest

      # Configuration de Node.js
      - name: Configuration de Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      # Configuration de GitHub Pages
      - name: Configuration de Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: nuxt

      # Cache pour les builds plus rapides
      - name: Cache de build Nuxt
        uses: actions/cache@v4
        with:
          path: |
            dist
            .nuxt
            node_modules/.vite
            node_modules/.cache
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-

      # Installation des dépendances
      - name: Installer les dépendances
        run: pnpm install --frozen-lockfile

      # Génération du site statique
      - name: Générer le site statique avec Nuxt
        run: pnpm run generate

      # Téléchargement de l'artefact pour GitHub Pages
      - name: Télécharger l'artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Tâche de déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
